-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."participants" add column "is_approved" boolean
--  not null default 'false';
